"""Deterministic multi-level documentation synthesis."""

from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from knowcode.data_models import Entity, EntityKind, RelationshipKind
from knowcode.storage.knowledge_store import KnowledgeStore
from knowcode.utils.entity_identity import ensure_entity_content_hash


_DOC_ENTITY_KINDS = {
    EntityKind.MODULE,
    EntityKind.DOCUMENT,
    EntityKind.SECTION,
    EntityKind.CONFIG_KEY,
    EntityKind.CLASS,
    EntityKind.FUNCTION,
    EntityKind.METHOD,
    EntityKind.VARIABLE,
}

_API_ENTITY_KINDS = {
    EntityKind.CLASS,
    EntityKind.FUNCTION,
    EntityKind.METHOD,
    EntityKind.CONFIG_KEY,
}


@dataclass(frozen=True)
class DocumentationBundle:
    """Generated documentation files and the manifest that describes them."""

    documents: dict[str, str]
    manifest: dict[str, Any]


class DocumentationSynthesizer:
    """Generate architecture, module, and entity documentation from a store.

    The synthesizer is intentionally deterministic and local-only. It creates
    useful reviewable docs without requiring model access, while leaving room for
    future LLM-generated narratives to consume the same manifest and structure.
    """

    MANIFEST_FILENAME = "documentation_manifest.json"

    def __init__(
        self,
        store: KnowledgeStore,
        *,
        generated_at: str | None = None,
    ) -> None:
        self.store = store
        self.generated_at = generated_at or datetime.now(timezone.utc).isoformat(
            timespec="seconds"
        )

    def generate(self) -> DocumentationBundle:
        """Generate all documentation files and a freshness manifest."""
        by_file = self._entities_by_file()
        documents: dict[str, str] = {
            "index.md": self._render_index(by_file),
            "architecture.md": self._render_architecture(by_file),
        }

        for file_path, entities in sorted(by_file.items()):
            documents[self._module_doc_path(file_path)] = self._render_module(
                file_path,
                entities,
            )

        manifest = self._build_manifest(documents, by_file)
        return DocumentationBundle(documents=documents, manifest=manifest)

    def write(self, output_dir: str | Path) -> DocumentationBundle:
        """Write generated documentation files to ``output_dir``."""
        output_path = Path(output_dir)
        bundle = self.generate()

        for relative_path, content in bundle.documents.items():
            target = output_path / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

        manifest_path = output_path / self.MANIFEST_FILENAME
        manifest_path.write_text(
            json.dumps(bundle.manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return bundle

    def _entities_by_file(self) -> dict[str, list[Entity]]:
        grouped: dict[str, list[Entity]] = {}
        for entity in self.store.entities.values():
            if entity.kind not in _DOC_ENTITY_KINDS:
                continue
            grouped.setdefault(entity.location.file_path, []).append(entity)

        for entities in grouped.values():
            entities.sort(key=self._entity_sort_key)
        return grouped

    def _render_index(self, by_file: dict[str, list[Entity]]) -> str:
        source_entities = self._source_entities(by_file)
        lines = [
            "# Codebase Documentation",
            "",
            "Generated by KnowCode.",
            "",
            "## Overview",
            "",
            f"- Source files: {len(by_file)}",
            f"- Tracked entities: {len(source_entities)}",
            f"- Relationships: {len(self.store.relationships)}",
            "",
            "## Architecture",
            "",
            "- [System Architecture](architecture.md)",
            "",
            "## Modules",
            "",
        ]

        if not by_file:
            lines.append("No source files were present in the knowledge store.")
        else:
            for file_path, entities in sorted(by_file.items()):
                summary = self._module_summary_sentence(entities)
                lines.append(
                    f"- [{file_path}]({self._module_doc_path(file_path)}) - {summary}"
                )

        lines.append("")
        return "\n".join(lines)

    def _render_architecture(self, by_file: dict[str, list[Entity]]) -> str:
        entities = self._source_entities(by_file)
        kind_counts = Counter(entity.kind.value for entity in entities)
        language_counts = Counter(self._language_for(entity) for entity in entities)
        relationship_counts = Counter(rel.kind.value for rel in self.store.relationships)

        lines = [
            "# Architecture Overview",
            "",
            "## System Shape",
            "",
            (
                f"This knowledge store describes {len(entities)} tracked entities "
                f"across {len(by_file)} source files."
            ),
            "",
            "## Languages",
            "",
        ]
        lines.extend(self._counter_lines(language_counts))
        lines.extend(["", "## Entity Mix", ""])
        lines.extend(self._counter_lines(kind_counts))
        lines.extend(["", "## Relationship Mix", ""])
        lines.extend(self._counter_lines(relationship_counts))
        lines.extend(["", "## Key Modules", ""])

        if not by_file:
            lines.append("No modules were present in the knowledge store.")
        else:
            for file_path, entities in self._key_modules(by_file):
                lines.append(
                    f"- `{file_path}`: {self._module_summary_sentence(entities)}"
                )

        lines.append("")
        return "\n".join(lines)

    def _render_module(self, file_path: str, entities: list[Entity]) -> str:
        lines = [
            f"# Module: `{file_path}`",
            "",
            "## Summary",
            "",
            self._module_narrative(entities),
            "",
            "## Public API",
            "",
        ]

        api_entities = [
            entity for entity in entities if entity.kind in _API_ENTITY_KINDS
        ]
        if not api_entities:
            lines.append("No public API entities were identified for this file.")
        else:
            for entity in api_entities:
                lines.extend(self._render_entity(entity))
                lines.append("")

        lines.extend(["## Tracked Entities", ""])
        for entity in entities:
            location = self._format_location(entity)
            lines.append(
                f"- {entity.kind.value} `{entity.qualified_name}` "
                f"({location})"
            )

        lines.append("")
        return "\n".join(lines)

    def _render_entity(self, entity: Entity) -> list[str]:
        lines = [
            f"### {entity.kind.value} `{entity.qualified_name}`",
            "",
            (
                f"`{entity.qualified_name}` is a {entity.kind.value} defined at "
                f"`{self._format_location(entity)}`."
            ),
        ]
        if entity.signature:
            lines.append(f"Signature: `{entity.signature}`")
        if entity.docstring:
            lines.extend(["", self._first_paragraph(entity.docstring)])

        behavior_lines = self._format_behavior(entity)
        if behavior_lines:
            lines.extend(["", "Behavior:"])
            lines.extend(behavior_lines)

        relationship_lines = self._format_entity_relationships(entity)
        if relationship_lines:
            lines.extend(["", "Relationships:"])
            lines.extend(relationship_lines)

        return lines

    def _module_narrative(self, entities: list[Entity]) -> str:
        module_doc = self._module_docstring(entities)
        summary = self._module_summary_sentence(entities)
        if module_doc:
            return f"{module_doc}\n\n{summary}"
        return summary

    def _module_summary_sentence(self, entities: list[Entity]) -> str:
        counts = Counter(entity.kind.value for entity in entities)
        parts = [
            f"{count} {kind}{'' if count == 1 else 's'}"
            for kind, count in sorted(counts.items())
        ]
        entity_phrase = ", ".join(parts) if parts else "no tracked entities"
        incoming, outgoing = self._file_relationship_counts(entities)
        return (
            f"{entity_phrase}; {outgoing} outgoing and {incoming} incoming "
            "relationships."
        )

    def _module_docstring(self, entities: list[Entity]) -> str:
        for entity in entities:
            if (
                entity.kind in {EntityKind.MODULE, EntityKind.DOCUMENT}
                and entity.docstring
            ):
                return self._first_paragraph(entity.docstring)
        return ""

    def _format_behavior(self, entity: Entity) -> list[str]:
        behavior = entity.metadata.get("behavior")
        if not isinstance(behavior, dict):
            return []

        lines: list[str] = []
        side_effect_class = behavior.get("side_effect_class")
        if isinstance(side_effect_class, str) and side_effect_class:
            lines.append(f"- Side effect class: `{side_effect_class}`")

        for label, key in (
            ("Side effects", "side_effects"),
            ("Reads", "reads"),
            ("Writes", "writes"),
            ("Calls", "calls"),
        ):
            values = behavior.get(key)
            if isinstance(values, list) and values:
                lines.append(f"- {label}: {self._format_inline_code_list(values)}")

        confidence = behavior.get("confidence")
        if isinstance(confidence, (int, float)):
            lines.append(f"- Confidence: {confidence:.2f}")

        return lines

    def _format_entity_relationships(self, entity: Entity) -> list[str]:
        callers = sorted(self.store.get_callers(entity.id), key=self._entity_sort_key)
        callees = sorted(self.store.get_callees(entity.id), key=self._entity_sort_key)
        children = sorted(self.store.get_children(entity.id), key=self._entity_sort_key)

        lines: list[str] = []
        if callees:
            lines.append(f"- Calls: {self._format_entities(callees)}")
        if callers:
            lines.append(f"- Called by: {self._format_entities(callers)}")
        if children:
            lines.append(f"- Contains: {self._format_entities(children)}")
        return lines

    def _build_manifest(
        self,
        documents: dict[str, str],
        by_file: dict[str, list[Entity]],
    ) -> dict[str, Any]:
        entity_hashes: dict[str, str] = {}
        source_files: dict[str, dict[str, Any]] = {}

        for file_path, entities in sorted(by_file.items()):
            file_hash_parts: list[str] = []
            entity_ids: list[str] = []
            for entity in entities:
                content_hash = self._entity_hash(entity)
                entity_hashes[entity.id] = content_hash
                entity_ids.append(entity.id)
                file_hash_parts.append(f"{entity.id}:{content_hash}")

            source_files[file_path] = {
                "entity_count": len(entities),
                "entity_ids": entity_ids,
                "content_hash": self._sha256_lines(file_hash_parts),
                "doc_path": self._module_doc_path(file_path),
            }

        return {
            "schema_version": 1,
            "generator": "knowcode.documentation_synthesizer",
            "generated_at": self.generated_at,
            "documents": sorted(documents),
            "stats": {
                "source_files": len(by_file),
                "tracked_entities": sum(
                    len(entities) for entities in by_file.values()
                ),
                "relationships": len(self.store.relationships),
            },
            "source_files": source_files,
            "entity_hashes": entity_hashes,
        }

    def _source_entities(self, by_file: dict[str, list[Entity]]) -> list[Entity]:
        return [entity for entities in by_file.values() for entity in entities]

    def _key_modules(
        self,
        by_file: dict[str, list[Entity]],
        limit: int = 10,
    ) -> list[tuple[str, list[Entity]]]:
        ranked = sorted(
            by_file.items(),
            key=lambda item: (
                -len(item[1]),
                -sum(self._file_relationship_counts(item[1])),
                item[0],
            ),
        )
        return ranked[:limit]

    def _file_relationship_counts(
        self,
        entities: list[Entity],
    ) -> tuple[int, int]:
        entity_ids = {entity.id for entity in entities}
        incoming = 0
        outgoing = 0
        for relationship in self.store.relationships:
            if relationship.kind not in {
                RelationshipKind.CALLS,
                RelationshipKind.IMPORTS,
                RelationshipKind.REFERENCES,
            }:
                continue
            source_in_file = relationship.source_id in entity_ids
            target_in_file = relationship.target_id in entity_ids
            if source_in_file and not target_in_file:
                outgoing += 1
            if target_in_file and not source_in_file:
                incoming += 1
        return incoming, outgoing

    @staticmethod
    def _counter_lines(counter: Counter[str]) -> list[str]:
        if not counter:
            return ["- none: 0"]
        return [f"- {key}: {counter[key]}" for key in sorted(counter)]

    @staticmethod
    def _entity_sort_key(entity: Entity) -> tuple[str, int, int, str]:
        return (
            entity.location.file_path,
            entity.location.line_start,
            entity.location.line_end,
            entity.qualified_name,
        )

    @staticmethod
    def _format_location(entity: Entity) -> str:
        return (
            f"{entity.location.file_path}:"
            f"{entity.location.line_start}-{entity.location.line_end}"
        )

    @staticmethod
    def _first_paragraph(text: str) -> str:
        stripped = text.strip()
        if not stripped:
            return ""
        return stripped.split("\n\n", 1)[0].replace("\n", " ")

    @staticmethod
    def _format_entities(entities: list[Entity], limit: int = 8) -> str:
        names = [entity.qualified_name for entity in entities[:limit]]
        formatted = DocumentationSynthesizer._format_inline_code_list(names)
        remaining = len(entities) - limit
        if remaining > 0:
            return f"{formatted}, +{remaining} more"
        return formatted

    @staticmethod
    def _format_inline_code_list(values: list[Any]) -> str:
        strings = [str(value) for value in values if str(value)]
        return ", ".join(f"`{value}`" for value in strings)

    @staticmethod
    def _language_for(entity: Entity) -> str:
        language = entity.metadata.get("language")
        if isinstance(language, str) and language:
            return language

        suffix = Path(entity.location.file_path).suffix.lower()
        return {
            ".md": "markdown",
            ".py": "python",
            ".yaml": "yaml",
            ".yml": "yaml",
            ".js": "javascript",
            ".jsx": "javascript",
            ".ts": "typescript",
            ".tsx": "typescript",
            ".java": "java",
            ".rs": "rust",
            ".vue": "vue",
        }.get(suffix, suffix.lstrip(".") or "unknown")

    @staticmethod
    def _module_doc_path(file_path: str) -> str:
        safe = re.sub(r"[^A-Za-z0-9_.-]+", "__", file_path.strip("/\\"))
        return f"modules/{safe or 'root'}.md"

    @staticmethod
    def _entity_hash(entity: Entity) -> str:
        ensure_entity_content_hash(entity)
        content_hash = entity.metadata.get("content_hash")
        return content_hash if isinstance(content_hash, str) else ""

    @staticmethod
    def _sha256_lines(lines: list[str]) -> str:
        payload = "\n".join(sorted(lines))
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()
